### ISSUE TITLE
Remake directory failed

### ISSUE THREAD

**Issue by johanmaia** [kimmobrunfeldt/concurrently#108]
In **package.json**
```
"delsrc": "if exist src rd src /s /q",
"makesrc": "if not exist src mkdir .\\src",
"buildsrc": "concurrently \"npm run delsrc\" \"npm run makesrc\"",
```
This one of examples when the second script need to do a checkup, it generates a bug without displaying an error.
In this case, if you run "buildsrc" the first time, that seems to be all right. But, if you run it a second time, the src folder is removed but not made again. It seems to be the check up "if not exist" which would be run before "delsrc". Is it a real bug ? There is an other way to do this ?

**Comment by gustavohenke** [comment]
You'll inevitably have concurrency problems here, because you're telling your OS to run `delsrc` and `makesrc` at the same time. One of them may "win" and actually do its task.

You should probably look into not using concurrently for this.
For example, `npm run delsrc && npm run makesrc` should be enough.

I'm not sure however if this syntax works on Windows by default 😐
