### ISSUE TITLE
"Exit with code 1" (but the scripts exit with 0)

### ISSUE THREAD

**Issue by rap2hpoutre** [kimmobrunfeldt/concurrently#150]
Running this script:

    "watch": "concurrently \"riot -w --ext html tags js/src/tags.js\" \"babel js/src --out-dir js/dist --watch\"",

If I break with `CTRL`+`C`: it returns an error

```
[1] babel js/src --out-dir js/dist --watch exited with code null
[0] riot -w --ext html tags js/src/tags.js exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@1.0.0 watch: `concurrently "riot -w --ext html tags js/src/tags.js" "babel js/src --out-dir js/dist --watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

So this is a strange behavior : the subscripts exited with code null, but not concurrently (fresh install).

Is this the normal behavior?

Thank you for your work!

**Comment by sant123** [comment]
I get errno 130 😞

**Comment by gustavohenke** [comment]
Hello folks,
First of all, sorry for the delay.

Secondly, the problem with the `null` exit code is a known one. It probably means a `SIGINT`, as you pressed <kbd>Ctrl</kbd> + <kbd>C</kbd>.

Finally, I think you get the error code `1` because the scripts didn't finish with code `0` (success). This is the default behaviour, which can be tweaked a bit with the use of `--success` flag.

I acknowledge there's space for concurrently to not fail in these cases, as they are an interruption _caused by the user_, not by something wrong that happened in the process.

**Comment by gustavohenke** [comment]
Reference from CLI tools: https://github.com/ember-cli/ember-cli/issues/6421
