### ISSUE TITLE
Custom prefix

### ISSUE THREAD

**Issue by benjick** [kimmobrunfeldt/concurrently#16]
Hey

Would it be possible to use a custom prefix? Instead of index I would like something like "client:index" so it shows up as client:0 or client:1 etc.

The reason for this is I start both my server and client with make which gives me two processes that are called 0 and two that are called 1. I would want to separate them a bit to make it more clear which process is doing what

**Comment by kimmobrunfeldt** [comment]
That would be possible yeah. I'm not sure how much more informative the prefix becomes if instead of 0, you have client:0. Anyways, I'm happy to merge a pull request for this feature if someone wants to implement it. I would prefer this to be implemented so that the --prefix option would have to be one of these: `index`, `pid`, `command`, `none`, and in any other case, it would try to fill a template, where each of those values are given as variables. That would allow users to specify for example: `--prefix "client:{{index}}"`

**Comment by benjick** [comment]
The reasoning for this i launch two concurrent, one for the server and one for the client from a Makefile, this gives me two processes named 0, two named 1 etc etc.

**Comment by kimmobrunfeldt** [comment]
This is possible in the new release: https://github.com/kimmobrunfeldt/concurrently/releases/tag/2.0.0

For example: `concurrently --prefix "client:{index}" ..`

**Comment by benjick** [comment]
Thanks!
