### ISSUE TITLE
concurrently vs npm-run-all

### ISSUE THREAD

**Issue by dcorb** [kimmobrunfeldt/concurrently#180]
There was a movement to consolidate all similar projects under one umbrella, npm-run-all, some years ago:
https://github.com/mysticatea/npm-run-all/issues/10
where Kimmo participated

I think I'm not the only one who wonders, what's the difference between these two solutions?
Since popularity, is at the moment the same for both projects:
https://www.npmtrends.com/concurrently-vs-npm-run-all-vs-parallelshell

**Comment by mrozbarry** [comment]
I think the big difference is concurrently runs _anything_ where npm-run-all is specific to package.json scripts, and does extra things because of special knowledge of package.json and node.

I think it makes sense that concurrently remains it's own package, in spite of my preference to have a "one tool that does one job." I think these goals are difference enough.

**Comment by jcollum-nike** [comment]
I had to ditch concurrently today because it was giving an 1 exit code for 3 processes that exited with SIGTERM or 0. Did not have that problem with `npm-run-all`.

**Comment by gustavohenke** [comment]
Hello! I'm sorry that I took so long in answering this ticket.

Interesting to see that there was work to consolidate tools -- thanks for raising that, @dcorb!

---

> concurrently runs anything where npm-run-all is specific to package.json scripts, and does extra things because of special knowledge of package.json and node.

Yep, I think that sums it up. I haven't looked at npm-run-all in a while though, maybe it has improved since.

We have since added special support for npm (and then yarn) because these are so popular, and since concurrently is written in JS, it most likely implies that you will be using those tools too.

Does that answer you, @dcorb?

---

> I had to ditch concurrently today because it was giving an 1 exit code for 3 processes that exited with SIGTERM or 0. Did not have that problem with npm-run-all.

@jcollum-nike would you be willing to improve concurrently by providing your feedback on an issue that I could help triage?

**Comment by gustavohenke** [comment]
Ah, nvm @jcollum-nike. I see you have opened #187. 🙂
