### ISSUE TITLE
Run each concurrent command in its own window

### ISSUE THREAD

**Issue by Waltari10** [kimmobrunfeldt/concurrently#182]
Hey,

Is there an option to run each concurrent command in its own terminal window or tab?

**Comment by kimmobrunfeldt** [comment]
I agree with @mrmurphy. 

Before concurrently, I used a tmux to run multiple commands in the same window: https://github.com/kimmobrunfeldt/frontend-starter/blob/master/tools/tmux. It has its benefits, but also makes things more complex: do you want to be able to have separate cursors/scrollback for the different commands, what are the keyboard shortcuts to scroll etc. IMO, implementing that with concurrently makes this module too complex, because other tools, like tmux already exist.

**Comment by OliverJAsh** [comment]
I've been using [iTermocil](https://github.com/TomAnthony/itermocil) for this.
