### ISSUE TITLE
Whitespace Truncates original command by one character

### ISSUE THREAD

**Issue by Jonathan002** [kimmobrunfeldt/concurrently#194]
Concurrently v4.1.1

I've noticed that adding whitespace removes the last character of the command inputed.

e.g.
```
// Command ran is ngin instead of nginx
concurrently \"nginx \"
[0] /bin/sh: 1: ngin: not found
[1]  exited with code 0
[0] ngin exited with code 127
```

Although it works perfectly fine when no space is added.
```
// Expected behavior
concurrently \"nginx\"
[0] nginx: [emerg] invalid number of arguments in "user" directive in /data/etc/nginx/nginx.conf:2
[0] nginx exited with code 1
```

I've also noticed an issue similar to this here: https://github.com/kimmobrunfeldt/concurrently/issues/118

Just wanted to report this. Thanks

**Comment by gustavohenke** [comment]
Thanks for the report.
Yeah the quote stripping logic didn't handle impaired quotes -- I pushed a fix for it.

If you add a trailing space, my fix will not make your command line run though: concurrently will receive 2 commands, `\"nginx` and ` \"`. That's because you're wrapping the quotes when you don't need to.
