### ISSUE TITLE
How could i use these controllers?

### ISSUE THREAD

**Issue by yanguoyu** [kimmobrunfeldt/concurrently#218]
https://github.com/kimmobrunfeldt/concurrently/blob/af501f3d3ed1771e0933ceaab9b157481c3868b3/index.js#L50
before these Export you has use module.exports, How could i import these controllers?

**Comment by gustavohenke** [comment]
Hello!
Those can be used just like in the main concurrently function:

https://github.com/kimmobrunfeldt/concurrently/blob/af501f3d3ed1771e0933ceaab9b157481c3868b3/index.js#L12-L46

The idea is that you can build your own concurrently with each piece.
Let's say you'd rather have logging to a file, instead of to stdout -- that's fine, just instantiate your own `Logger` instance and pass it to the other controllers that add the features (logging command output, restarting, killing on signal, etc).
