### ISSUE TITLE
Should I install concurrently as a devdependency or normal dependency?

### ISSUE THREAD

**Issue by sander1095** [kimmobrunfeldt/concurrently#273]
Hello!

I have an Angular project and I want to use concurrently. 

Currently I have it installed as a normal dependency (not globally). But I feel like it would make more sense to have this as a `devdependency`; it's not a real dependency as it is only used in my case for development

What is the right thing to do :)?

**Comment by gustavohenke** [comment]
Hey!
I'd say that any dependency that you need to run your program in production should go in `dependencies`. This advice doesn't apply only to concurrently 😊 

For example, if what you're writing is a CLI tool, then it's likely that you'll want concurrently in `dependencies`.
Likewise if your `npm start` uses concurrently, and in your production server you're running `npm start`.

Otherwise, sounds like it should really go in `devDependencies`!
