### ISSUE TITLE
Colors not displaying with prefix enabled

### ISSUE THREAD

**Issue by ljwagerfield** [kimmobrunfeldt/concurrently#49]
I've noticed colors are only displayed by my `webpack` child process when using the `--raw` flag.

However, the `--raw` flag seems to disable prefixes.

Is it possible to have the child processes output their color _and_ keep the prefixes I've assigned to them?

(Would _love_ to have my cake and eat it! :D)

**Comment by kimmobrunfeldt** [comment]
This isn't so easy because to preserve original colors output by webpack, we need to directly pipe webpack stdout without modifying it in between.

I'm open to a separate `--no-colors` flag if someone figures out how to preserve the original colors and modify the output. Last time when I investigated this, I couldn't find a reliable way for it.

**Comment by kimmobrunfeldt** [comment]
Meanwhile you can try to find if webpack has a `--color` flag which forces it to use colors in output and remove the `--raw` attribute. See: https://github.com/kimmobrunfeldt/concurrently/issues/8#issuecomment-184901271

**Comment by aecz** [comment]
If child process uses chalk, just set FORCE_COLOR=1 (using cross-env for example).
Also you can set NPM_CONFIG_COLOR=always.
Concurrently could set those variables automatically. Adding a flag --force-colors would be nice.

**Comment by gustavohenke** [comment]
Hey guys, check #86 for some context on how this was fixed.

**Comment by gustavohenke** [comment]
Published [v3.2.0](https://github.com/kimmobrunfeldt/concurrently/releases/tag/3.2.0)!
