### ISSUE TITLE
Searching for maintainers with me

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/concurrently#51]
Hi,

concurrently has become a bit more popular nowadays and issues keep up piling. I would love to help with all issues but I don't have time to do everything.

If you are interested to join me maintaining and developing this tool, please raise your interest by commenting to this issue and shortly describing what you could help with.

PS. I'm currently on a vacation and will get back to maintaining this repo in a few weeks. Sorry for the delays, I know a lot of people are waiting for fixes.

Thanks everyone!

**Comment by gustavohenke** [comment]
Hi!
It looks like it's been a while since you first posted this.
So, finally! I'm raising my hand 🖐 

I'm readily available to help you by triaging issues and reviewing/accepting PRs.
I'm usually able to find some hours every week to push some new code, too.

This is basically how I'm operating at [ctavan/express-validator](https://github.com/ctavan/express-validator), which I have been happily maintaining.

Something about my background is available at my profile here and at [npm](https://www.npmjs.com/~gustavohenke) 😁

**Comment by kimmobrunfeldt** [comment]
Hi @gustavohenke! Sounds awesome. I've been very inactive in Github for the last few months, sorry for the late response.

I added you as a member now.

**Comment by gustavohenke** [comment]
Thanks!

**Comment by filipesilva** [comment]
I'd like to help as well. I use concurrently a lot and think it's great, so would like to give back.

**Comment by gcca** [comment]
Count on me to develop new code and review PRs.

**Comment by kimmobrunfeldt** [comment]
@filipesilva Added you as a contributor.

**Comment by gustavohenke** [comment]
🎉 since Kimmo added another (very) active OSS contributor, I'll close this issue!

**Comment by kimmobrunfeldt** [comment]
@filipesilva What is your NPM account so I could add you as a contributor there too?

**Comment by kimmobrunfeldt** [comment]
Added you both as collaborators to https://github.com/kimmobrunfeldt/spawn-default-shell repo too. It's very closely tied to concurrently

**Comment by filipesilva** [comment]
Heya @kimmobrunfeldt, thanks for adding me! I'm subscribed to the notifications so I can try to fix stuff when it comes up. If you have some specific issues you'd like me to look at, let me know. I work on Windows so can debug general windows stuff easily.

My npm acc is the same name as the github one, `filipesilva`: https://www.npmjs.com/~filipesilva
