### ISSUE TITLE
Some child processes turn off color output

### ISSUE THREAD

**Issue by ilkka** [kimmobrunfeldt/concurrently#8]
For example Typesafe Activator switches to monochrome output when running under concurrently. It'd be super nice if you could cheat & swindle it to output colors instead (unless of course concurrently's output was directed to a file). Dunno if this is possible or if child processes *always* know how their output stream works.

**Comment by jeffbski** [comment]
+1 I noticed browser-sync and mocha also end up with no color, however nodemon's color still works

**Comment by kimmobrunfeldt** [comment]
Do you have ideas of how this could be fixed?

**Comment by ilkka** [comment]
[Apparently](http://stackoverflow.com/a/1402389) a Linux tool called [script](http://linux.die.net/man/1/script) does this. Dunno yet how but it's an interesting problem, might take a look at the source :D

**Comment by jeffbski** [comment]
I noticed that https://github.com/keithamus/parallelshell a similar child process runner doesn't have this issue so parallel children's output retains its color, maybe there is a clue in its code? It could be that it shares the original out stream and doesn't pipe it.

**Comment by ArnaudRinquin** [comment]
Same with Karma

**Comment by adambuczynski** [comment]
Also happens with gulp task runner, colors of that child process are lost, even when running with `--raw`

**Comment by kimmobrunfeldt** [comment]
I guess this is related to the way we are piping stdout/stderr when using child_process.spawn function.

**Comment by adambuczynski** [comment]
Thanks for the fix, is this going to be included in an upcoming release?

**Comment by kimmobrunfeldt** [comment]
Yeah I will do a release in a moment after testing all new features.

**Comment by kimmobrunfeldt** [comment]
Ok so the issue is now partly fixed. The reason why this happens is explained in these Stack Overflow answers:

* http://stackoverflow.com/questions/18825493/retaining-output-colors-when-shelling-out-to-node
* http://stackoverflow.com/questions/9135579/node-js-spawn-with-colors

The new release fixes the problem so that `--raw` will use `stdio: 'inherit'` which makes the colors work. In   other cases you can use e.g. `--color` flag for the command to force it to use color output even though the stdout is a pipe instead of a tty.

Summary, use one of:

* `concurrently --raw ...`
* `concurrentl "mycommand --color"` note: this is just e.g. chalk's convention to force coloring in output

**Comment by adambuczynski** [comment]
Alright I'll take it for a spin

**Comment by devboell** [comment]
Thanks, `--raw` fixed it for me: mocha colors are there and cursor doesn't disappear

**Comment by Nexxado** [comment]
Thank you for the fix @kimmobrunfeldt.
on Windows, for me it wont show colors if i run webpack via npm script, but it works if i run webpack using `webpack ...` command.
